<?php
declare(strict_types=1);

/**
 * Manifest voor pers- en mediabestanden.
 * Zet available op true én plaats het bestand onder assets/media/press/…
 * Alleen dan verschijnt een download op /media.
 *
 * Pad is relatief aan de webroot (begint met /assets/…).
 */
return [
    'usage_rights' => 'Dit materiaal mag redactioneel worden gebruikt in publicaties over Stop met wilskracht, Korne Pot of een gerelateerde bijeenkomst of samenwerking. Foto’s: eigen werk van Korne Pot, tenzij anders vermeld. Voor commercieel gebruik of ander gebruik: neem contact op via info@kornepot.nl.',

    'items' => [
        [
            'id' => 'cover-high',
            'category' => 'book-cover',
            'title' => 'Boekomslag Stop met wilskracht',
            'description' => 'Definitieve omslag van het boek Stop met wilskracht.',
            'path' => '/assets/img/cover.png',
            'filename' => 'stop-met-wilskracht-omslag.png',
            'type' => 'image/png',
            'dimensions' => '682 × 1024 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'cover-web',
            'category' => 'book-cover',
            'title' => 'Boekomslag (web)',
            'description' => 'Webversie van de omslag.',
            'path' => '/assets/img/cover.png',
            'filename' => 'stop-met-wilskracht-omslag.png',
            'type' => 'image/png',
            'dimensions' => '682 × 1024 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'cover-mockup',
            'category' => 'book-cover',
            'title' => 'Boekmockup (transparant)',
            'description' => 'PNG-mockup voor artikelen en social posts.',
            'path' => '/assets/media/press/book-cover/grippartner-cover-mockup.png',
            'filename' => 'grippartner-cover-mockup.png',
            'type' => 'image/png',
            'dimensions' => '',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => false,
            'status_label' => 'Mockup volgt',
        ],
        [
            'id' => 'author-landscape',
            'category' => 'author',
            'title' => 'Auteursfoto liggend',
            'description' => 'Korne Pot bij de boekenkast — liggend formaat (3:2).',
            'path' => '/assets/media/press/author/korne-pot-landscape.jpg',
            'filename' => 'korne-pot-landscape.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '2560 × 1707 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'author-portrait',
            'category' => 'author',
            'title' => 'Auteursfoto staand',
            'description' => 'Korne Pot — staand formaat (2:3), geschikt voor artikelen en bio’s.',
            'path' => '/assets/media/press/author/korne-pot-portrait.jpg',
            'filename' => 'korne-pot-portrait.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '1280 × 1920 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'author-square',
            'category' => 'author',
            'title' => 'Auteursfoto vierkant',
            'description' => 'Korne Pot — vierkant, geschikt voor social en avatars.',
            'path' => '/assets/media/press/author/korne-pot-square.jpg',
            'filename' => 'korne-pot-square.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '1920 × 1920 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'author-bookshelf-wide',
            'category' => 'author',
            'title' => 'Auteursfoto boekenkast (breed)',
            'description' => 'Origineel breed beeld bij de boekenkast.',
            'path' => '/assets/media/press/hires/korne-pot-bookshelf-wide-hires.jpg',
            'filename' => 'korne-pot-bookshelf-wide.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '2560 × 1920 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'author-office',
            'category' => 'author',
            'title' => 'Auteursfoto kantoor',
            'description' => 'Korne Pot op kantoor.',
            'path' => '/assets/media/press/hires/korne-pot-office-hires.jpg',
            'filename' => 'korne-pot-office.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '2560 × 1920 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'media-podcast-studio',
            'category' => 'illustrations',
            'title' => 'Podcast / interview (studio)',
            'description' => 'Opname in de podcaststudio — bruikbaar bij interview-aankondigingen.',
            'path' => '/assets/media/press/media/korne-pot-podcast-studio.jpg',
            'filename' => 'korne-pot-podcast-studio.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '2560 × 1705 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'media-podcast-bookshelf',
            'category' => 'illustrations',
            'title' => 'Podcast / interview (boekenkast)',
            'description' => 'Korne Pot met headset en microfoon.',
            'path' => '/assets/media/press/media/korne-pot-podcast-bookshelf.jpg',
            'filename' => 'korne-pot-podcast-bookshelf.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '2560 × 1705 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'media-awardshow',
            'category' => 'illustrations',
            'title' => 'Event / awardshow',
            'description' => 'Korne Pot op een mediashow / awardavond.',
            'path' => '/assets/media/press/media/korne-pot-awardshow.jpg',
            'filename' => 'korne-pot-awardshow.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '2560 × 1920 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'media-award-tiktok',
            'category' => 'illustrations',
            'title' => 'Award The Best Social Awards',
            'description' => 'Winnaar Beste Merk op TikTok — The Best Social Awards.',
            'path' => '/assets/media/press/media/korne-pot-award-tiktok.jpg',
            'filename' => 'korne-pot-award-tiktok.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '2560 × 1242 px',
            'size_label' => '',
            'creator' => 'Korne Pot',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'media-lezing',
            'category' => 'illustrations',
            'title' => 'Lezing / keynote (beeld)',
            'description' => 'Beeld voor lezing-aankondigingen. Let op: AI-ondersteund beeld op basis van bestaande foto’s — geen documentaire podiumfoto.',
            'path' => '/assets/media/press/media/korne-pot-lezing.jpg',
            'filename' => 'korne-pot-lezing.jpg',
            'type' => 'image/jpeg',
            'dimensions' => '2400 × 1600 px',
            'size_label' => '',
            'creator' => 'Korne Pot / gegenereerd beeld',
            'credit' => 'Korne Pot',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'logo-wordmark',
            'category' => 'logos',
            'title' => 'Woordmerk Grippartner',
            'description' => 'Tijdelijk woordmerk voor vermelding naast artikelen. Vervangbaar door definitief logo.',
            'path' => '/assets/media/press/logos/grippartner-woordmerk.png',
            'filename' => 'grippartner-woordmerk.png',
            'type' => 'image/png',
            'dimensions' => '2000 × 1333 px',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => true,
            'status_label' => '',
        ],
        [
            'id' => 'logo-wordmark-svg',
            'category' => 'logos',
            'title' => 'Woordmerk Grippartner (SVG)',
            'description' => 'Vectorversie van het woordmerk — volgt.',
            'path' => '/assets/media/press/logos/grippartner-woordmerk.svg',
            'filename' => 'grippartner-woordmerk.svg',
            'type' => 'image/svg+xml',
            'dimensions' => '',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => false,
            'status_label' => 'SVG volgt',
        ],
        [
            'id' => 'social-square',
            'category' => 'social',
            'title' => 'Social asset vierkant (1080×1080)',
            'description' => 'Concepttemplate voor Instagram / LinkedIn. Geen definitieve campagnevisual.',
            'path' => '/assets/media/press/social/grippartner-social-1080x1080.png',
            'filename' => 'grippartner-social-1080x1080.png',
            'type' => 'image/png',
            'dimensions' => '1080 × 1080 px',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => false,
            'status_label' => 'Concept volgt (na definitieve omslag)',
        ],
        [
            'id' => 'social-portrait',
            'category' => 'social',
            'title' => 'Social asset portret (1080×1350)',
            'description' => 'Concepttemplate. Geen definitieve campagnevisual.',
            'path' => '/assets/media/press/social/grippartner-social-1080x1350.png',
            'filename' => 'grippartner-social-1080x1350.png',
            'type' => 'image/png',
            'dimensions' => '1080 × 1350 px',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => false,
            'status_label' => 'Concept volgt (na definitieve omslag)',
        ],
        [
            'id' => 'social-story',
            'category' => 'social',
            'title' => 'Social asset story (1080×1920)',
            'description' => 'Concepttemplate voor stories. Geen definitieve campagnevisual.',
            'path' => '/assets/media/press/social/grippartner-social-1080x1920.png',
            'filename' => 'grippartner-social-1080x1920.png',
            'type' => 'image/png',
            'dimensions' => '1080 × 1920 px',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => false,
            'status_label' => 'Concept volgt (na definitieve omslag)',
        ],
        [
            'id' => 'social-linkedin',
            'category' => 'social',
            'title' => 'LinkedIn liggend (1200×627)',
            'description' => 'Concepttemplate. Geen definitieve campagnevisual.',
            'path' => '/assets/media/press/social/grippartner-social-1200x627.png',
            'filename' => 'grippartner-social-1200x627.png',
            'type' => 'image/png',
            'dimensions' => '1200 × 627 px',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => false,
            'status_label' => 'Concept volgt (na definitieve omslag)',
        ],
        [
            'id' => 'kit-zip',
            'category' => 'documents',
            'title' => 'Complete mediakit (ZIP)',
            'description' => 'ZIP met factsheet, teksten, omslag, foto’s en logo.',
            'path' => '/assets/media/press/documents/grippartner-mediakit.zip',
            'filename' => 'grippartner-mediakit.zip',
            'type' => 'application/zip',
            'dimensions' => '',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => false,
            'status_label' => 'Complete mediakit volgt',
        ],
        [
            'id' => 'factsheet-pdf',
            'category' => 'documents',
            'title' => 'Factsheet (PDF)',
            'description' => 'Printklare factsheet. Tot die tijd: gebruik /media#factsheet en print via de browser.',
            'path' => '/assets/media/press/documents/grippartner-factsheet.pdf',
            'filename' => 'grippartner-factsheet.pdf',
            'type' => 'application/pdf',
            'dimensions' => '',
            'size_label' => '',
            'creator' => '',
            'credit' => '',
            'rights' => 'redactioneel',
            'available' => false,
            'status_label' => 'PDF volgt — print nu via de factsheet op deze pagina',
        ],
    ],
];
